package inicio;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.AbstractBorder;
import stocksmart.FontLoader;
import stocksmart.FrameAltas;
import stocksmart.FrameCategoria;
import stocksmart.FrameClientes;
import stocksmart.FrameDevoluciones;
import stocksmart.FrameMovimientos;
import stocksmart.FramePedidos;
import stocksmart.FrameProductos;
import stocksmart.FrameProveedores;
import stocksmart.FrameReportePedidos;
import stocksmart.FrameReporteVentas;
import stocksmart.FrameSubproductos;
import stocksmart.FrameUnidades;
import stocksmart.FrameUsuarios;
import stocksmart.FrameVentas;

public class FrameMenu extends javax.swing.JFrame {
    
        FrameClientes fclientes = null;
        FramePedidos fpedidos = null;
        FrameProductos fproductos = null;
        FrameProveedores fproveedores = null;
        FrameUsuarios fusuarios = null;
        FrameReportePedidos freportepedidos = null;
        FrameReporteVentas freporteventas = null;
        FrameVentas fventas = null;
        FrameMovimientos fmovimientos = null;
        FrameAltas faltas = null;
        FrameDevoluciones fdevoluciones = null;
        FrameUnidades funidades = null;
        FrameSubproductos fsubproductos = null;
        FrameCategoria fcategorias = null;

        Font customFontBold = FontLoader.customFontBold;
        Font customFontBold3 = FontLoader.customFontBold3;

    /**
     * Creates new form StockSmartFrameMenu
     */
    public FrameMenu() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin1 = new javax.swing.JPanel();
        panelLogin2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        botonVentas = new javax.swing.JButton();
        botonPedidos = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonProductos = new javax.swing.JButton();
        botonProveedores = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        botonReportePedidos = new javax.swing.JButton();
        botonReporteVentas = new javax.swing.JButton();
        botonMovimientos = new javax.swing.JButton();
        botonCategorias = new javax.swing.JButton();
        botonRDevoluciones = new javax.swing.JButton();
        botonUnidades = new javax.swing.JButton();
        botonSubproductos = new javax.swing.JButton();
        botonAltas = new javax.swing.JButton();
        botonPrediccion = new javax.swing.JButton();
        botonDevoluciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelLogin1.setBackground(new java.awt.Color(50, 130, 233));

        panelLogin2.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(50, 130, 233));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Menú");

        botonVentas.setBackground(new java.awt.Color(50, 130, 233));
        botonVentas.setFont(customFontBold3);
        botonVentas.setForeground(new java.awt.Color(255, 255, 255));
        botonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/ventas-icon_google24.png"))); // NOI18N
        botonVentas.setText("Ventas");
        botonVentas.setBorder(null);
        botonVentas.setBorderPainted(false);
        botonVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonVentas.setIconTextGap(6);
        botonVentas.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/ventas-icon_google20.png"))); // NOI18N
        botonVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        botonPedidos.setBackground(new java.awt.Color(50, 130, 233));
        botonPedidos.setFont(customFontBold3);
        botonPedidos.setForeground(new java.awt.Color(255, 255, 255));
        botonPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/package-icon24.png"))); // NOI18N
        botonPedidos.setText("Pedidos");
        botonPedidos.setBorder(null);
        botonPedidos.setBorderPainted(false);
        botonPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPedidos.setIconTextGap(6);
        botonPedidos.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonPedidos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/package-icon20.png"))); // NOI18N
        botonPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidosActionPerformed(evt);
            }
        });

        botonClientes.setBackground(new java.awt.Color(50, 130, 233));
        botonClientes.setFont(customFontBold3);
        botonClientes.setForeground(new java.awt.Color(255, 255, 255));
        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/clientes-icon24.png"))); // NOI18N
        botonClientes.setText("Clientes");
        botonClientes.setBorder(null);
        botonClientes.setBorderPainted(false);
        botonClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonClientes.setIconTextGap(6);
        botonClientes.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonClientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/clientes-icon20.png"))); // NOI18N
        botonClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        botonProductos.setBackground(new java.awt.Color(50, 130, 233));
        botonProductos.setFont(customFontBold3);
        botonProductos.setForeground(new java.awt.Color(255, 255, 255));
        botonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/productos-icon24.png"))); // NOI18N
        botonProductos.setText("Productos");
        botonProductos.setBorder(null);
        botonProductos.setBorderPainted(false);
        botonProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProductos.setIconTextGap(6);
        botonProductos.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonProductos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/inventory-icon-20.png"))); // NOI18N
        botonProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosActionPerformed(evt);
            }
        });

        botonProveedores.setBackground(new java.awt.Color(50, 130, 233));
        botonProveedores.setFont(customFontBold3);
        botonProveedores.setForeground(new java.awt.Color(255, 255, 255));
        botonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/proveedores-icon24.png"))); // NOI18N
        botonProveedores.setText("Proveedores");
        botonProveedores.setBorder(null);
        botonProveedores.setBorderPainted(false);
        botonProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonProveedores.setIconTextGap(6);
        botonProveedores.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonProveedores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/proveedores-icon20.png"))); // NOI18N
        botonProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedoresActionPerformed(evt);
            }
        });

        botonUsuarios.setBackground(new java.awt.Color(50, 130, 233));
        botonUsuarios.setFont(customFontBold3);
        botonUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/usuarios-icon24.png"))); // NOI18N
        botonUsuarios.setText("Usuarios");
        botonUsuarios.setBorder(null);
        botonUsuarios.setBorderPainted(false);
        botonUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonUsuarios.setIconTextGap(6);
        botonUsuarios.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonUsuarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/usuarios-icon20.png"))); // NOI18N
        botonUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });

        botonReportePedidos.setBackground(new java.awt.Color(50, 130, 233));
        botonReportePedidos.setFont(customFontBold3);
        botonReportePedidos.setForeground(new java.awt.Color(255, 255, 255));
        botonReportePedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporteVentasPedidos24.png"))); // NOI18N
        botonReportePedidos.setText("Reporte Pedidos");
        botonReportePedidos.setBorder(null);
        botonReportePedidos.setBorderPainted(false);
        botonReportePedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReportePedidos.setIconTextGap(6);
        botonReportePedidos.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonReportePedidos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporteVentasPedidos20.png"))); // NOI18N
        botonReportePedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonReportePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportePedidosActionPerformed(evt);
            }
        });

        botonReporteVentas.setBackground(new java.awt.Color(50, 130, 233));
        botonReporteVentas.setFont(customFontBold3);
        botonReporteVentas.setForeground(new java.awt.Color(255, 255, 255));
        botonReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporteVentasPedidos24.png"))); // NOI18N
        botonReporteVentas.setText("Reporte Ventas");
        botonReporteVentas.setBorder(null);
        botonReporteVentas.setBorderPainted(false);
        botonReporteVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonReporteVentas.setIconTextGap(6);
        botonReporteVentas.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonReporteVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporteVentasPedidos20.png"))); // NOI18N
        botonReporteVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteVentasActionPerformed(evt);
            }
        });

        botonMovimientos.setBackground(new java.awt.Color(50, 130, 233));
        botonMovimientos.setFont(customFontBold3);
        botonMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        botonMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/movimientos-icon24.png"))); // NOI18N
        botonMovimientos.setText("Movimientos");
        botonMovimientos.setBorder(null);
        botonMovimientos.setBorderPainted(false);
        botonMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMovimientos.setIconTextGap(6);
        botonMovimientos.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonMovimientos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/configuration-icon20.png"))); // NOI18N
        botonMovimientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMovimientosActionPerformed(evt);
            }
        });

        botonCategorias.setBackground(new java.awt.Color(50, 130, 233));
        botonCategorias.setFont(customFontBold3);
        botonCategorias.setForeground(new java.awt.Color(255, 255, 255));
        botonCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/categoria-icon24.png"))); // NOI18N
        botonCategorias.setText("Categorías");
        botonCategorias.setBorder(null);
        botonCategorias.setBorderPainted(false);
        botonCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCategorias.setIconTextGap(6);
        botonCategorias.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonCategorias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/clientes-icon20.png"))); // NOI18N
        botonCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoriasActionPerformed(evt);
            }
        });

        botonRDevoluciones.setBackground(new java.awt.Color(50, 130, 233));
        botonRDevoluciones.setFont(customFontBold3);
        botonRDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        botonRDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporte-dev-icon24.png"))); // NOI18N
        botonRDevoluciones.setText("Reporte de Devoluciones");
        botonRDevoluciones.setBorder(null);
        botonRDevoluciones.setBorderPainted(false);
        botonRDevoluciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRDevoluciones.setIconTextGap(6);
        botonRDevoluciones.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonRDevoluciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/package-icon20.png"))); // NOI18N
        botonRDevoluciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRDevolucionesActionPerformed(evt);
            }
        });

        botonUnidades.setBackground(new java.awt.Color(50, 130, 233));
        botonUnidades.setFont(customFontBold3);
        botonUnidades.setForeground(new java.awt.Color(255, 255, 255));
        botonUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/unidad-icon24.png"))); // NOI18N
        botonUnidades.setText("Unidades");
        botonUnidades.setBorder(null);
        botonUnidades.setBorderPainted(false);
        botonUnidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonUnidades.setIconTextGap(6);
        botonUnidades.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonUnidades.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/proveedores-icon20.png"))); // NOI18N
        botonUnidades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnidadesActionPerformed(evt);
            }
        });

        botonSubproductos.setBackground(new java.awt.Color(50, 130, 233));
        botonSubproductos.setFont(customFontBold3);
        botonSubproductos.setForeground(new java.awt.Color(255, 255, 255));
        botonSubproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/subproducto-icon24.png"))); // NOI18N
        botonSubproductos.setText("Subproductos");
        botonSubproductos.setBorder(null);
        botonSubproductos.setBorderPainted(false);
        botonSubproductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSubproductos.setIconTextGap(6);
        botonSubproductos.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonSubproductos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/reporteVentasPedidos20.png"))); // NOI18N
        botonSubproductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSubproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubproductosActionPerformed(evt);
            }
        });

        botonAltas.setBackground(new java.awt.Color(50, 130, 233));
        botonAltas.setFont(customFontBold3);
        botonAltas.setForeground(new java.awt.Color(255, 255, 255));
        botonAltas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/altas-icon24.png"))); // NOI18N
        botonAltas.setText("Altas");
        botonAltas.setBorder(null);
        botonAltas.setBorderPainted(false);
        botonAltas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAltas.setIconTextGap(6);
        botonAltas.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonAltas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/configuration-icon20.png"))); // NOI18N
        botonAltas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltasActionPerformed(evt);
            }
        });

        botonPrediccion.setBackground(new java.awt.Color(50, 130, 233));
        botonPrediccion.setFont(customFontBold3);
        botonPrediccion.setForeground(new java.awt.Color(255, 255, 255));
        botonPrediccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/prediccion-icon24.png"))); // NOI18N
        botonPrediccion.setText("Predicción");
        botonPrediccion.setBorder(null);
        botonPrediccion.setBorderPainted(false);
        botonPrediccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPrediccion.setIconTextGap(6);
        botonPrediccion.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonPrediccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/usuarios-icon20.png"))); // NOI18N
        botonPrediccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPrediccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrediccionActionPerformed(evt);
            }
        });

        botonDevoluciones.setBackground(new java.awt.Color(50, 130, 233));
        botonDevoluciones.setFont(customFontBold3);
        botonDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        botonDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/devolucion-icon24.png"))); // NOI18N
        botonDevoluciones.setText("Devoluciones");
        botonDevoluciones.setBorder(null);
        botonDevoluciones.setBorderPainted(false);
        botonDevoluciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDevoluciones.setIconTextGap(6);
        botonDevoluciones.setMargin(new java.awt.Insets(2, 14, 25, 14));
        botonDevoluciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/icons/configuration-icon20.png"))); // NOI18N
        botonDevoluciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogin2Layout = new javax.swing.GroupLayout(panelLogin2);
        panelLogin2.setLayout(panelLogin2Layout);
        panelLogin2Layout.setHorizontalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin2Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(517, 517, 517))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin2Layout.createSequentialGroup()
                        .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLogin2Layout.createSequentialGroup()
                                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLogin2Layout.createSequentialGroup()
                                        .addComponent(botonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(botonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLogin2Layout.createSequentialGroup()
                                        .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelLogin2Layout.createSequentialGroup()
                                                .addComponent(botonReportePedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(botonReporteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelLogin2Layout.createSequentialGroup()
                                                .addComponent(botonCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botonPrediccion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(31, 31, 31)
                                        .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonRDevoluciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonSubproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin2Layout.createSequentialGroup()
                                .addComponent(botonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(botonProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botonUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))))
        );
        panelLogin2Layout.setVerticalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonPrediccion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLogin2Layout.createSequentialGroup()
                        .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRDevoluciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin2Layout.createSequentialGroup()
                                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonSubproductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonReportePedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonReporteVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonMovimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAltas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(botonCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLogin1Layout = new javax.swing.GroupLayout(panelLogin1);
        panelLogin1.setLayout(panelLogin1Layout);
        panelLogin1Layout.setHorizontalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelLogin1Layout.setVerticalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        //AbstractBorder brdr1 = new TextBubbleBorder(new Color(255, 255, 255),4,25,0);
        //panelLogin2.setBorder(brdr1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
           
        try {
            
            if(this.fventas == null){
                this.fventas = new FrameVentas(this);
            }
                
            this.fventas.setVisible(true);
            this.setVisible(false);
                
        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidosActionPerformed
        
        try {

            if(this.fpedidos == null){
                this.fpedidos = new FramePedidos(this);
            }

            this.fpedidos.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_botonPedidosActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        
        try {

            if(this.fclientes == null){
                this.fclientes = new FrameClientes(this);
            }

            this.fclientes.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosActionPerformed
        
        try {

            if(this.fproductos == null){
                this.fproductos = new FrameProductos(this);
            }

            this.fproductos.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_botonProductosActionPerformed

    private void botonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedoresActionPerformed
        
        try {

            if(this.fproveedores == null){
                this.fproveedores = new FrameProveedores(this);
            }

            this.fproveedores.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_botonProveedoresActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        
        try {
                
            if(this.fusuarios == null){
                this.fusuarios = new FrameUsuarios(this);
            }

            this.fusuarios.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonReportePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportePedidosActionPerformed
        
        try {
                
            if(this.freportepedidos == null){
                this.freportepedidos = new FrameReportePedidos(this);
            }

            this.freportepedidos.setVisible(true);
            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_botonReportePedidosActionPerformed

    private void botonReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteVentasActionPerformed
        
        if(this.freporteventas == null){
            
            try {
                this.freporteventas = new FrameReporteVentas(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.freporteventas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonReporteVentasActionPerformed

    private void botonMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMovimientosActionPerformed
        
        if(this.fmovimientos == null){
             
            try {
                this.fmovimientos = new FrameMovimientos(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.fmovimientos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonMovimientosActionPerformed

    private void botonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoriasActionPerformed
        
        if(this.fcategorias == null){
            
            try {
                this.fcategorias = new FrameCategoria(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.fcategorias.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonCategoriasActionPerformed

    private void botonRDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRDevolucionesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonRDevolucionesActionPerformed

    private void botonUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnidadesActionPerformed
        
        if(this.funidades == null){
            
            try {
                this.funidades = new FrameUnidades(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.funidades.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonUnidadesActionPerformed

    private void botonSubproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubproductosActionPerformed
        
        if(this.fsubproductos == null){
             
            try {
                this.fsubproductos = new FrameSubproductos(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.fsubproductos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonSubproductosActionPerformed

    private void botonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltasActionPerformed
        
        if(this.faltas == null){
            
            try {
                this.faltas = new FrameAltas(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.faltas.setVisible(true);
        this.setVisible(false);
     
    }//GEN-LAST:event_botonAltasActionPerformed

    private void botonPrediccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrediccionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botonPrediccionActionPerformed

    private void botonDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionesActionPerformed
                
        if(this.fdevoluciones == null){
            
            try {
                this.fdevoluciones = new FrameDevoluciones(this);
            } catch (SQLException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        this.fdevoluciones.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonDevolucionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAltas;
    private javax.swing.JButton botonCategorias;
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonDevoluciones;
    private javax.swing.JButton botonMovimientos;
    private javax.swing.JButton botonPedidos;
    private javax.swing.JButton botonPrediccion;
    private javax.swing.JButton botonProductos;
    private javax.swing.JButton botonProveedores;
    private javax.swing.JButton botonRDevoluciones;
    private javax.swing.JButton botonReportePedidos;
    private javax.swing.JButton botonReporteVentas;
    private javax.swing.JButton botonSubproductos;
    private javax.swing.JButton botonUnidades;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonVentas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelLogin1;
    private javax.swing.JPanel panelLogin2;
    // End of variables declaration//GEN-END:variables
}